name: Docker Build

on:
  workflow_dispatch:
    inputs:
      myInput:
        description: 'User Input:'
        required: true
        default: "Hello World"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DBNAME: ${{ secrets.DBNAME }}
      DBUSER: ${{ secrets.DBUSER }}
      DBPASS: ${{ secrets.DBPASS }}
      HOST: ${{ secrets.HOST }}
      DBPORT: ${{ secrets.DBPORT }}
      CR_REGISTRY: ${{ secrets.CR_REGISTRY }}
      CR_REPO: app
      IMAGE_TAG: ${{ github.sha }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        ref: main
    - name: Yandex Cloud CR "Login" Action for GitHub Actions
      uses: yc-actions/yc-cr-login@v0.1-alpha
      with:
        yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
    - name: Build, tag, and push image to Yandex Cloud Container Registry
      run: |
        docker build --platform=linux/amd64 --pull --rm -f "Dockerfile" --build-arg DBUSER=$DBUSER --build-arg DBNAME=$DBNAME --build-arg HOST=$HOST --build-arg DBPORT=$DBPORT --build-arg DBPASS=$DBPASS -t app:latest "." 
        docker tag app cr.yandex/$CR_REGISTRY/app:latest
        docker push cr.yandex/$CR_REGISTRY/app:latest

    - name: YC Serverless Container Deploy
      uses: yc-actions/yc-sls-container-deploy@v2
      with:
        yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
        folder-id: ${{ secrets.FOLDER_ID }}
        container-name: mainapp
        revision-service-account-id: ${{ secrets.SERVICE_ACCOUNT_ID }}
        revision-cores: 1
        revision-memory: 128Mb
        revision-core-fraction: 5
        revision-concurrency: 8
        revision-image-url: cr.yandex/${{ secrets.CR_REGISTRY }}/app:latest
        revision-execution-timeout: 10
